name: Validate HTML and CSS

on:
  push:
    branches:
      - main
      - master

jobs:
  html-css-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML files
        uses: Cyb3r-Jak3/html5validator-action@v0.4.0
        with:
          root: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install csslint
        run: npm install -g csslint

      - name: Validate CSS files
        run: |
          find . -name "*.css" -print0 | xargs -0 csslint || true
