name: Validate HTML and CSS

on:
  push:
    branches:
      - main
      - master

jobs:
  html-css-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate HTML files
        uses: Cyb3r-Jak3/html5validator-action@v0.4.0
        with:
          root: .

      - name: Validate CSS files
        uses: csslint/csslint@v1.0.5
        run: |
          npm install -g csslint
          find . -name "*.css" -print0 | xargs -0 csslint || true
