name: Validate HTML and CSS

on:
  push:
    branches:
      - main
      - master

jobs:
  html-css-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install html5validator
        run: pip install html5validator

      - name: Validate HTML files
        run: |
          find . -name "*.html" -print0 | xargs -0 -I{} html5validator --root . --files {}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install csslint
        run: npm install -g csslint

      - name: Validate CSS files
        run: |
          find . -name "*.css" -print0 | xargs -0 csslint || true
